New database system
Scope-SL/Scope pull request #11
Opened 2021-12-15 22:03 UTC by Monaldcry7788

I know that the pr is a little confusional, but idk why this appear.

2021-12-15 22:07 UTC, TheUltiOne commented
Why are there 3 different PRs?

2021-12-16 00:19 UTC, NaoUnderscore requested changes

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.Server/Database/Collections/ClientCollection.cs
> +    /// A class which contains client information.
Change to _A tool to handle clients information for database solutions._

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.Server/Database/Collections/ClientCollection.cs
> +        /// <param name="rawId">Client raw id.</param>
Use 's

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.Server/Database/Collections/ClientCollection.cs
> +        /// Gets the client raw id.
Use 's

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.Server/Database/Database.cs
> +        internal static string Folder => "Server folder";
Server folder? Really e.e?

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.Server/Database/Database.cs
> +                Log.Error($"Error when try to load database:\n {e.StackTrace}\n {e.Message}");
Change to _Error whilst trying to load the database..._

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.Server/Database/Database.cs
> +        /// Method for close server database.
Change to _Closes the database_

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.Server/Database/Database.cs
> +        /// Method for load server database.
Change to _Opens the database_

2021-12-16 00:19 UTC, NaoUnderscore commented on Scope.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Scope.Server", "..\..\source\repos\Scope\Scope.Server\Scope.Server.csproj", "{DC7D4A88-D775-4B7D-A273-578C9B0F476E}"
You can't reference your local path

2021-12-16 16:18 UTC, TheUltiOne requested changes
Add “The” before “client’s”

2021-12-17 00:02 UTC, NaoUnderscore requested changes
You must reference the project in the solution

2021-12-18 21:26 UTC, NaoUnderscore approved these changes

2021-12-18 21:31 UTC, xRoier approved these changes

2021-12-19 01:05 UTC, merged